export const Embeds = [
    {
        id: 1,
        title: "Anything",
        label: "Anything",
        type: "url",
        url: "",
        htmlRegex: "",
        regex: /[(http(s)?):\\/\\/(www\\.)?a-zA-Z0-9@:%._\\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)/,
        image: require("@/assets/images/svg/anything.svg"),
    },
    {
        id: 2,
        title: "Sheets",
        label: "Google Sheets",
        type: "url",
        regex: /^https?:\/\/docs\.google\.com\/spreadsheets\/d\/([a-zA-Z0-9-_]{44}|[a-zA-Z0-9-_]{19})(\/.*)?$/,
        url: "",
        image: require("@/assets/images/svg/googlesheets.svg"),
    },
    {
        id: 3,
        title: "Docs",
        label: "Google Docs",
        type: "url",
        regex :/^https?:\/\/docs\.google\.com\/document\/d\/([a-zA-Z0-9-_]{44}|[a-zA-Z0-9-_]{19})(\/.*)?$/,
        url: "",
        image: require("@/assets/images/svg/Googledocs.svg"),
    },
    {
        id: 4,
        title: "Youtube",
        label: "Youtube",
        regex:/^(?:https?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})(?:\S+)?$/,
        type: "url",
        url: "",
        image: require("@/assets/images/svg/Youtube.svg"),
    },
    {
        id: 5,
        title: "Figma",
        label: "Figma",
        regex:/^(?:https:\/\/)?(?:www\.)?figma\.com\/(file|proto)\/([0-9a-zA-Z]{22,128})(?:\/?([^]+)?(.*))?$/,
        type: "url",
        url: "",
        image: require("@/assets/images/svg/figma.svg"),
    },
]
