/** MONGODB SCHEMA TYPE **/
const SCHEMA_TYPE = {
    TIMESHEET: "timesheets",
    HISTORY: "history",
    USERID: "userId",
    MILESTONE: "milestone",
    USERS: "users",
    ADMIN_DETAIL: "adminDetail",
    WASABICREDENTIALS: "wasabicredentials",
    PROJECT_MAIN_TEMPLATES: "ProjectTemplate",
    TIMETRACKER_DOWNLOAD: "timeTrackerDownload",
    COMPANIES: "companies",
    PROJECT_TEMPLATES: "project_templates",
    PROJECT_TAB_COMPONENTS: "project_tab_components",
    PROJECT_STATUS_TEMPLATES: "project_status_template",
    TASK_TYPE_TEMPLATES: "task_type_templates",
    TASK_STATUS_TEMPLATES: "task_status_templates",
    TEAMS_MANAGEMENT: "teams_management",
    COMPANY_USERS: "company_users",
    RULES: "rules",
    ESTIMATES_TIME: "estimated_time",
    CURRENCY_LIST: "currency_list",
    PROJECTS: "projects",
    SETTINGS: "settings",
    APPS: "apps",
    NOTIFICATIONS: "notifications",
    NOTIFICATIONS_SETTINGS: "notifications_settings",
    MENTIONS: "mentions",
    TASKS: "tasks",
    COMMON:"common",
    MAIN_CHATS: "main_chats",
    GOLBAL : "global",
    COMMENTS: "comments",
    PROJECT_RULES:"projectRules",
    SUBSCRIPTIONPLAN: "subscriptionPlan",
    PLANFEATURE: "planFeature",
    PLANFEATUREDISPLAY: "planFeatureDisplay",
    SUBSCRIPTIONS: 'subscriptions',
    INVOICES: 'invoices',
    CREDITNOTES: 'creditNotes',
    PRECOMPANIES: 'preCompanies',
    CUSTOM_FIELDS: "customField",
    SPRINTS:"sprints",
    FOLDERS: "folders",
    RESTRICTED_EXTENSIONS: "restrictedExtensions",
    GLOBAL_CUSTOM_FIELDS: "global_custom_fields",
    TOURS: "tours",
}

module.exports = {
    SCHEMA_TYPE
};